AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Continuous Development Environment


Parameters:
  BaseDomain:
    Description: Base domain for the app
    Type: String
  CertificateArn:
    Description: Certificate ARN
    Type: String
  Cloud9InstanceType:
    Description: Cloud9 EC2 Instance Type
    Type: String
    Default: t3.large
  RoleSSO:
    Description: Federation Role Name
    Type: String
  User:
    Description: Federated User email address
    Type: String


Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./library/vpc.yml
      Parameters:
        Cidr: 10.0.0.0/16
        Subnets: !Join
          - ','
          - - 10.0.1.0/24
            - 10.0.2.0/24

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./library/load-balancer.yml
      Parameters:
        Vpc: !GetAtt VpcStack.Outputs.Vpc
        Subnets: !GetAtt VpcStack.Outputs.Subnets
        CertificateArn: !Ref CertificateArn
        BaseDomain: !Ref BaseDomain

  DevelopmentEnvironment:
    Type: AWS::Cloud9::EnvironmentEC2
    DependsOn: VpcStack
    Properties:
      AutomaticStopTimeMinutes: 30
      InstanceType: !Ref Cloud9InstanceType
      Name: !Ref AWS::StackName
      SubnetId: !GetAtt VpcStack.Outputs.Subnet1
      OwnerArn: !Sub 'arn:aws:sts::${AWS::AccountId}:assumed-role/${RoleSSO}/${User}'
