AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Resources

Parameters:
  Cidr:
    Description: Vpc Cidr
    Type: String
  Subnets:
    Description: Vpc Subnets list
    Type: List<String>

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref Cidr
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: {  }

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  DhcpOption:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: 'ec2.internal'
      DomainNameServers:
      - AmazonProvidedDNS

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  Route:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref RouteTable
      GatewayId: !Ref InternetGateway
    DependsOn: GatewayAttachment

  SubnetAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref Vpc

  InSubnetAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref SubnetAcl
      RuleNumber: '32000'
      Protocol: '-1'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: '-1'
        Type: '-1'
      PortRange:
        From: '1'
        To: '65535'

  OutSubnetAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref SubnetAcl
      RuleNumber: '32000'
      Protocol: '-1'
      RuleAction: allow
      Egress: 'true'
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: '-1'
        Type: '-1'
      PortRange:
        From: '1'
        To: '65535'

  Zone1:
    Type: AWS::CloudFormation::Stack
    DependsOn: GatewayAttachment
    Properties:
      TemplateURL: zone.yml
      Parameters:
        Range: 1
        CidrBlock: !Select [ 0, !Ref Subnets  ]
        Vpc: !Ref Vpc
        NetworkAclId: !Ref SubnetAcl
        RouteTableId: !Ref RouteTable
        AvailabilityZone:
          Fn::Select:
          - 0
          - Fn::GetAZs: ''

  Zone2:
    Type: AWS::CloudFormation::Stack
    DependsOn: GatewayAttachment
    Properties:
      TemplateURL: zone.yml
      Parameters:
        Range: 2
        CidrBlock: !Select [ 1, !Ref Subnets  ]
        Vpc: !Ref Vpc
        NetworkAclId: !Ref SubnetAcl
        RouteTableId: !Ref RouteTable
        AvailabilityZone:
          Fn::Select:
          - 1
          - Fn::GetAZs: ''

Outputs:
  Vpc:
    Description: VPC
    Value: !Ref Vpc
  AvailabilityZones:
    Description: Availability zones actually used
    Value: !Join
    - ','
    - - !GetAtt Zone1.Outputs.AvailabilityZone
      - !GetAtt Zone2.Outputs.AvailabilityZone
  Subnets:
    Description: Subnets
    Value: !Join
    - ','
    - - !GetAtt Zone1.Outputs.Subnet
      - !GetAtt Zone2.Outputs.Subnet
  Subnet1:
    Description: Subnet 1
    Value: !GetAtt Zone1.Outputs.Subnet
  Subnet2:
    Description: Subnet 2
    Value: !GetAtt Zone2.Outputs.Subnet
  RouteTable:
    Description: Vpc route table
    Value: !Ref RouteTable